myform_form/myform_form/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("signup10_affichage/", views.signup10_affichage, name="signup10_affichage"),
    path("signup20_widget/", views.signup20_widget, name="signup20_widget"),
    path("signup30_data/", views.signup30_data, name="signup30_data"),
    path("signup30_data/signup30_reussi/", views.signup30_reussi, name="signup30_reussi"),
    path("signup31_data/", views.signup31_data, name="signup31_data"),
    path("signup31_affichage/", views.signup31_affichage, name="signup31_affichage"),
]

myform_form/myform_form/forms.py
from django import forms

JOBS = (
    ('Python', 'Python Developper'),
    ('JavaScript', 'JavaScript Developper'),
    ('Java', 'Java Developper')
)
CITIES = (
    ('Tanger', 'Capitale du nord'),
    ('Fes', 'Capitale culturelle'),
    ('Rabat', 'Capitale administrative'),
    ('Casablanca', 'Capitale economique')
)
LANGUAGES = (
    ('Ar', 'Arabic'),
    ('En', 'English'),
    ('sp', 'Spanish'),
    ('Fr', 'French')
)


class SignupForm(forms.Form):
    pseudo = forms.CharField(max_length=8, required=False)
    email = forms.EmailField()
    password = forms.CharField(min_length=6)
    jobs = forms.ChoiceField(choices=JOBS)
    city = forms.ChoiceField(choices=CITIES)
    language = forms.ChoiceField(choices=LANGUAGES)
    cgu_accept = forms.BooleanField(initial=True)

class SignupFormWidget(forms.Form):
    pseudo = forms.CharField(max_length=8, required=False)
    email = forms.EmailField()
    password = forms.CharField(min_length=6, widget=forms.PasswordInput)
    jobs = forms.ChoiceField(choices=JOBS, widget=forms.RadioSelect)
    city = forms.MultipleChoiceField(choices=CITIES, widget=forms.CheckboxSelectMultiple)
    language = forms.MultipleChoiceField(choices=LANGUAGES, widget=forms.SelectMultiple)
    cgu_accept = forms.BooleanField(initial=True)

class SignupFormData(forms.Form) :
    pseudo = forms.CharField(max_length=8, required=False)
    email = forms.EmailField()
    password = forms.CharField(min_length=6, widget=forms.PasswordInput)
    jobs = forms.ChoiceField(choices=JOBS, widget=forms.RadioSelect)
    language = forms.MultipleChoiceField(choices=LANGUAGES, widget=forms.CheckboxSelectMultiple)
    cgu_accept = forms.BooleanField(initial=True)

myform_form/myform_form/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse

from .forms import SignupForm, SignupFormWidget, SignupFormData


# Create your views here.
def signup10_affichage(request):
    form = SignupForm()
    return render(request, "myform_form/signup10_affichage.html", context={"form": form})


def signup20_widget(request):
    form = SignupFormWidget()
    return render(request, "classroom/signup20_widget.html", context={"form": form})


def signup30_data(request):
    if request.method == "POST":
        form = SignupFormData(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            return redirect(reverse("signup30_reussi"))
    else:
        form = SignupFormData()

    return render(request, "myform_form/signup30_data.html", context={"form": form})


def signup30_reussi(request):
    return render(request, "myform_form/signup30_reussi.html")


def signup31_data(request):
    form = SignupFormData()
    return render(request, "myform_form/signup31_data.html", context={"form": form})


def signup31_affichage(request):
    form = SignupFormData(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        print(cd)
        return render(request, 'myform_form/signup31_affichage.html', {"cd": cd})
    else:
        return HttpResponse("'Les données ne sont pas valides")

myform_form/myform_form/templates/classroom/signup20_widget.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Utilisation de l'attribut widge</title>
</head>
<body>
    <form action="" method="POST">
    {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
    </form>
</body>
</html>

myform_form/myform_form/templates/myform_form/Signup10_affichage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>form: affichage</title>
</head>
<body>
<table border=" 1">
    <tr>
        <th>Affichage par defaut</th>
        <th>**********</th>
        <th>Affichage as_p</th>
        <th>**********</th>
        <th>Affichage as_ul</th>
        <th>**********</th>
        <th>Affichage as_table</th>
    </tr>
    <tr>
        <td>
            <form action="" method="post" >
                {{form}}
            <p>
                <input type="submit" value="Submit"/>
            </p>
            </form>
        </td>
        <td>**********</td>
        <td>
            <form action="" method="post">
                {{ form.as_p }}
                <p>
                    <input type="submit" value="Submit"/>
                </p>
            </form>
        </td>
        <td>**********</td>
        <td>
            <form action="" method="post">
                {{ form.as_ul }}
                <p>
                    <input type="submit" value="Submit"/>
                </p>
            </form>
        </td>
        <td>**********</td>
        <td>
            <form action="" method="post">
                <table>
                    {{ form.as_table }}
                    <p>
                        <input type="submit" value="Submit" />
                    </p>
                 </table>
            </form>
        </td>
    </tr>
</table>
</body>
</html>

myform_form/myform_form/templates/myform_form/signup30_data.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Récuperer les données d'un formulair</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="S'inscrire">
        <!--<input type="hidden" name="csrfmiddlewaretoken" value="1DSKm2krEu2iTs6G1mILZfnsKfmaMAvoq@0pa101dKbMnTG0TFM01JKoEMtQbg2">
        <table>
            <tr>
                <th><label for="id_pseudo">Pseudo:</label></th>
            </tr>
        </table>-->
    </form>
</body>
</html>

myform_form/myform_form/templates/myform_form/signup30_reussi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Reussi</title>
</head>
<body>
    <h1>Merci de vous être inscrit</h1>
    <h2>Votre inscription a été éffectuée avec suscès</h2>
</body>
</html>

myform_form/myform_form/templates/myform_form/signup31_affichage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Affichage des données saisies</title>
</head>
<body>
    <h1>Données saisies</h1>
    <table border="1">
        <tr>
            <td>pseudo : </td>
            <td>{{ cd.pseudo }}/</td>
        </tr>
        <tr>
            <td>Email : </td>
            <td>{{ cd.email }}<td>
        </tr>
        <tr>
            <td>Password : </td>
            <td>{{ cd.password }}</td>
        </tr>
        <tr>
            <td>Job</td>
            <td>{{ cd.jobs }}</td>
        </tr>
        <tr>
            <td>Languages</td>
            <td>{{ cd.language }}</td>
        </tr>
    </table>
    <hr>
    <h2>Obtention automatique des clés et valeurs</h2>
    <table>
        {% for cle, valeur in cd.items %}
        <tr>
            <td>{{ cle }} : </td>
            <td>{{ valeur }}</td>
        </tr>
        {% endfor %}
    </table>
</body>
</html>

myform_form/myform_form/templates/myform_form/signup31_data.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Récuperer et afficher les données d'un formulaire</title>
</head>
<body>
    <form action="{%url 'signup31_affichage' %}" method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="s'inscrire">
    </form>
</body>
</html>